name: Publish to GitHub Packages
on:
  push:
    branches: ['main']
    paths:
      - '!website/**'
      - '!README.md'
      - '!.github/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nicolachoquet06250'
      - run: npm ci && npm run build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}